
[window]
# title: Term-Alacritty
dynamic_title = true
decorations = "Full"
padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16

[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/github_dark.toml"
]
