#!/bin/sh
apt-get update
apt-get -y install direnv
apt-get -y install kubectx
apt-get -y install fzf
apt-get -y install yamllint

# kubernetes comptions
mkdir -p ~/.local/share/bash-completion
kubectl completion bash > ~/.local/share/bash-completion/completions/kubectl

# get bat
BAT_VERSION=0.18.1
wget https://github.com/sharkdp/bat/releases/download/v${BAT_VERSION}/bat_${BAT_VERSION}_amd64.deb
sudo dpkg -i bat_${BAT_VERSION}_amd64.deb
rm bat_${BAT_VERSION}_amd64.deb

